# Site settings
title: Personal Webpage & Portfolio
email: nico@wyss.cx
description: This is my personal landing page. Contact me for more information!
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Nico Wyss
your-title: Data Science Student

# Social settings
500px_url:
facebook_url: 
github_url: https://github.com/Ermaconomist
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/wyss.photography/
linkedin_url: https://www.linkedin.com/in/nicowyss/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
